# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

orbs:
  javascript: wealthsimple/javascript@dev:master
  shell: wealthsimple/shell@dev:master

references:
  parameters: &parameters

jobs:
  semantic-release:
    executor: docker
    steps:
      - checkout
      - javascript/attach_code_workspace
      - javascript/yarn_install_dependencies
      - run: |
          npm set _auth "$NEXUS_CIRCLE_CI_TOKEN"
          export GITHUB_TOKEN="$DEVTOOLS_GITHUB_API_TOKEN"
          export NPM_TOKEN="$NEXUS_CIRCLE_CI_TOKEN"
          yarn workspaces run build
          yarn workspaces run semantic-release -e semantic-release-monorepo-config --npm-publish

  build:
    docker:
      - image: circleci/node:10.18
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run tests!
      - run: yarn test:all
      # Generate coverage
      - run: yarn test:coverage

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: wealthsimple
      - semantic-release:
          context: wealthsimple
          filters:
            branches:
              only: master